package com.file.vo;

public class Doc {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_doc.doc_id
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	private Integer docId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_doc.doc_name_o
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	private String docNameO;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_doc.doc_name_n
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	private String docNameN;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_doc.doc_dtime
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	private String docDtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_doc.doc_ctime
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	private String docCtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_doc.doc_size
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	private String docSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_doc.user_id
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	private Integer userId;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public Doc(Integer docId, String docNameO, String docNameN, String docDtime, String docCtime, String docSize,
			Integer userId) {
		this.docId = docId;
		this.docNameO = docNameO;
		this.docNameN = docNameN;
		this.docDtime = docDtime;
		this.docCtime = docCtime;
		this.docSize = docSize;
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public Doc() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_doc.doc_id
	 * @return  the value of t_doc.doc_id
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public Integer getDocId() {
		return docId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_doc.doc_id
	 * @param docId  the value for t_doc.doc_id
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public void setDocId(Integer docId) {
		this.docId = docId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_doc.doc_name_o
	 * @return  the value of t_doc.doc_name_o
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public String getDocNameO() {
		return docNameO;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_doc.doc_name_o
	 * @param docNameO  the value for t_doc.doc_name_o
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public void setDocNameO(String docNameO) {
		this.docNameO = docNameO == null ? null : docNameO.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_doc.doc_name_n
	 * @return  the value of t_doc.doc_name_n
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public String getDocNameN() {
		return docNameN;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_doc.doc_name_n
	 * @param docNameN  the value for t_doc.doc_name_n
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public void setDocNameN(String docNameN) {
		this.docNameN = docNameN == null ? null : docNameN.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_doc.doc_dtime
	 * @return  the value of t_doc.doc_dtime
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public String getDocDtime() {
		return docDtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_doc.doc_dtime
	 * @param docDtime  the value for t_doc.doc_dtime
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public void setDocDtime(String docDtime) {
		this.docDtime = docDtime == null ? null : docDtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_doc.doc_ctime
	 * @return  the value of t_doc.doc_ctime
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public String getDocCtime() {
		return docCtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_doc.doc_ctime
	 * @param docCtime  the value for t_doc.doc_ctime
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public void setDocCtime(String docCtime) {
		this.docCtime = docCtime == null ? null : docCtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_doc.doc_size
	 * @return  the value of t_doc.doc_size
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public String getDocSize() {
		return docSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_doc.doc_size
	 * @param docSize  the value for t_doc.doc_size
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public void setDocSize(String docSize) {
		this.docSize = docSize == null ? null : docSize.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_doc.user_id
	 * @return  the value of t_doc.user_id
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_doc.user_id
	 * @param userId  the value for t_doc.user_id
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", docId=").append(docId);
		sb.append(", docNameO=").append(docNameO);
		sb.append(", docNameN=").append(docNameN);
		sb.append(", docDtime=").append(docDtime);
		sb.append(", docCtime=").append(docCtime);
		sb.append(", docSize=").append(docSize);
		sb.append(", userId=").append(userId);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Doc other = (Doc) that;
		return (this.getDocId() == null ? other.getDocId() == null : this.getDocId().equals(other.getDocId()))
				&& (this.getDocNameO() == null ? other.getDocNameO() == null
						: this.getDocNameO().equals(other.getDocNameO()))
				&& (this.getDocNameN() == null ? other.getDocNameN() == null
						: this.getDocNameN().equals(other.getDocNameN()))
				&& (this.getDocDtime() == null ? other.getDocDtime() == null
						: this.getDocDtime().equals(other.getDocDtime()))
				&& (this.getDocCtime() == null ? other.getDocCtime() == null
						: this.getDocCtime().equals(other.getDocCtime()))
				&& (this.getDocSize() == null ? other.getDocSize() == null
						: this.getDocSize().equals(other.getDocSize()))
				&& (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getDocId() == null) ? 0 : getDocId().hashCode());
		result = prime * result + ((getDocNameO() == null) ? 0 : getDocNameO().hashCode());
		result = prime * result + ((getDocNameN() == null) ? 0 : getDocNameN().hashCode());
		result = prime * result + ((getDocDtime() == null) ? 0 : getDocDtime().hashCode());
		result = prime * result + ((getDocCtime() == null) ? 0 : getDocCtime().hashCode());
		result = prime * result + ((getDocSize() == null) ? 0 : getDocSize().hashCode());
		result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
		return result;
	}
}