package com.file.vo;

import java.io.Serializable;

public class User implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.user_id
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.user_name
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.user_pwd
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	private String userPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.user_ctime
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	private String userCtime;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public User(Integer userId, String userName, String userPwd, String userCtime) {
		this.userId = userId;
		this.userName = userName;
		this.userPwd = userPwd;
		this.userCtime = userCtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public User() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.user_id
	 * @return  the value of t_user.user_id
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.user_id
	 * @param userId  the value for t_user.user_id
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.user_name
	 * @return  the value of t_user.user_name
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.user_name
	 * @param userName  the value for t_user.user_name
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.user_pwd
	 * @return  the value of t_user.user_pwd
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public String getUserPwd() {
		return userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.user_pwd
	 * @param userPwd  the value for t_user.user_pwd
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd == null ? null : userPwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.user_ctime
	 * @return  the value of t_user.user_ctime
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public String getUserCtime() {
		return userCtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.user_ctime
	 * @param userCtime  the value for t_user.user_ctime
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	public void setUserCtime(String userCtime) {
		this.userCtime = userCtime == null ? null : userCtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", userId=").append(userId);
		sb.append(", userName=").append(userName);
		sb.append(", userPwd=").append(userPwd);
		sb.append(", userCtime=").append(userCtime);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		User other = (User) that;
		return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
				&& (this.getUserName() == null ? other.getUserName() == null
						: this.getUserName().equals(other.getUserName()))
				&& (this.getUserPwd() == null ? other.getUserPwd() == null
						: this.getUserPwd().equals(other.getUserPwd()))
				&& (this.getUserCtime() == null ? other.getUserCtime() == null
						: this.getUserCtime().equals(other.getUserCtime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
		result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
		result = prime * result + ((getUserPwd() == null) ? 0 : getUserPwd().hashCode());
		result = prime * result + ((getUserCtime() == null) ? 0 : getUserCtime().hashCode());
		return result;
	}
}