package com.file.mapper;

import java.util.List;
import java.util.Map;

import com.file.annotation.DocAnnotation;
import com.file.vo.Doc;
import com.file.vo.DocExample;
import org.apache.ibatis.annotations.Param;

@DocAnnotation
public interface DocMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	long countByExample(DocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	int deleteByExample(DocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	int deleteByPrimaryKey(Integer docId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	int insert(Doc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	int insertSelective(Doc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	List<Doc> selectByExample(DocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	Doc selectByPrimaryKey(Integer docId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Doc record, @Param("example") DocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	int updateByExample(@Param("record") Doc record, @Param("example") DocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	int updateByPrimaryKeySelective(Doc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Mon Sep 11 16:05:52 CST 2017
	 */
	int updateByPrimaryKey(Doc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_doc
	 * @mbg.generated  Fri Sep 08 16:20:24 CST 2017
	 */
//	int updateByPrimaryKey(Doc record);
//
//	boolean addDocByDoc(Doc doc);
//	
//	boolean delDocByUserIdAndDocId(int user_id,int doc_id);
//	
//	int getDocNumByUserId(int user_id);
//		
//	List<Doc> getDocsByPageAndUserId(Map<String, Object> map);
//
//	Doc getDocById(int doc_id);
	
}
